feat: add check for token presence

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -30,6 +30,16 @@ jobs:
         with:
           node-version: 20
 
+      - name: Check Token Presence
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "token missing"
+            exit 1
+          else
+            echo "token present"
+          fi
+
+
       - name: Install dependencies
         run: npm ci
 
